### PR TITLE
Adding test to confirm behavior

### PR DESCRIPTION
**Pull request by BrunoBernardino**
I was adding this test to confirm the behavior for fixing #4 and apparently it's already working?

Or am I misinterpreting the feature request @bryanhelmig ?

### CODE REVIEW

**Comment by bryanhelmig** [comment]
Ah yeah - this addresses @lvh-zapier's concerns - but I was thinking of the case when we don't censor values that are unknown before to us. For example - during the oauth authentication leg - we only know the `CLIENT_SECRET` - so we can censor that. But the response contains `access_token` which isn't part of our "censor bank" yet.

It would be smart to have logic that perhaps recursed the JSON responses or querystrings and automatically censored stuff with keys like `access_token`, `api_key`, etc. ([Sentry does something like this already in Python](https://github.com/getsentry/sentry/blob/8.10.0/src/sentry/constants.py#L166-L175)).

**Comment by lvh-zapier** [comment]
Huh, I'm confused. I thought this code censored anything of a given size by default already?

**Comment by lvh-zapier** [comment]
(Reminder: I should show y'all some redaction code we have internally, it may have some properties you care about.)

**Comment by bryanhelmig** [comment]
Yeah - I don't think this PR really addresses the core concern of that issue @lvh-zapier - it latched onto an off the cuff comment instead as I wasn't super clear.

**Comment by BrunoBernardino** [comment]
Seems that will require quite a few more things, so I'll merge this in for now and keep the issue open. Thanks for the clarification @bryanhelmig !

**Pull request merged**
